version: '3.7'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other GitLab configuration here
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'

  gerrit:
    image: 'gerritcodereview/gerrit:latest'
    container_name: gerrit
    environment:
      - CANONICAL_WEB_URL=http://gerrit.example.com
    ports:
      - '8080:8080'
      - '29418:29418'
    volumes:
      - 'gerrit-data:/var/gerrit/review_site'

  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    user: root
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - 'jenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gerrit-data:
  jenkins-data:
